/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.visionarios.vista;

import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import static java.lang.Thread.sleep;

/**
 *
 * @author dam
 */
public class JFApp extends javax.swing.JFrame {

    JPApp jpa = null;
    /**
     * Creates new form JFApp
     */
    public JFApp() {
        initComponents();
        jpa = new JPApp();
        this.setBounds(100, 100, 500, 500);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/recursos/visionariosIcon.jpg"));
        setIconImage(icon);
        this.setVisible(true);
        this.getContentPane().add(jpa);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }
    
    public void startAnimation() {
        while(true) {
            jpa.animarEstrellas();
            try {
                sleep(5);
            } catch (InterruptedException ex) {
                Logger.getLogger(JPApp.class.getName()).log(Level.SEVERE, null, ex);
            }
            jpa.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        JFApp jfa = new JFApp();
        jfa.startAnimation();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
