/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.visionarios.vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author dam
 */
public class JPApp extends javax.swing.JPanel {

    BufferedImage bg = null;
    BufferedImage visionarios = null;
    BufferedImage nube1 = null;
    BufferedImage nube2 = null;
    BufferedImage nube3 = null;
    BufferedImage haloMountain = null;
    BufferedImage haloScenario = null;
    SoundPlayer sp = null;
    /**
     * Creates new form JPApp
     */
    public JPApp() {
        initComponents();
        
        sp = new SoundPlayer(getClass().getResource("/recursos/musica2.wav"));
        sp.start();

        try {
            bg = ImageIO.read(getClass().getResource("/recursos/bg.png"));
            nube1 = ImageIO.read(getClass().getResource("/recursos/nube1.png"));
            nube2 = ImageIO.read(getClass().getResource("/recursos/nube2.png"));
            nube3 = ImageIO.read(getClass().getResource("/recursos/nube3.png"));
            visionarios = ImageIO.read(getClass().getResource("/recursos/visionarios.png"));
            haloMountain = ImageIO.read(getClass().getResource("/recursos/haloMountain.png"));
            haloScenario = ImageIO.read(getClass().getResource("/recursos/haloScenario.png"));
        } catch (IOException ex) {
            Logger.getLogger(JPApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    double width = screenSize.getWidth();
    double height = screenSize.getHeight();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    void animarEstrellas() {
    
    }
    
    private float grados = 0.1f;
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.drawImage(bg, 0, 0, getBounds().width, getBounds().height, null);
        
        // create the transform, note that the transformations happen
        // in reversed order (so check them backwards)
        AffineTransform at = new AffineTransform();

        // 4. translate it to the center of the component
        at.translate(getWidth() / 2, getHeight() / 2);

        // 3. do the actual rotation
        at.rotate(Math.PI / grados);


        // 1. translate the object so that you rotate it around the 
        //    center (easier :))
        at.translate(-bg.getWidth()/2, -bg.getHeight()/2);

        // draw the image
        g2d.drawImage(bg, at, null);

        g2d.drawImage(nube1, 0, 0, getBounds().width, getBounds().height, null);
        g2d.drawImage(nube2, 0, 0, getBounds().width, getBounds().height, null);
        g2d.drawImage(nube3, 0, 0, getBounds().width, getBounds().height, null);
        g2d.drawImage(haloScenario, 0, 0, getBounds().width, getBounds().height, null);
        g2d.drawImage(visionarios, 0, 0, getBounds().width, getBounds().height, null);
        g2d.drawImage(haloMountain, 0, 0, getBounds().width, getBounds().height, null);
        grados = grados + 0.1f;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
