/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.visionarios.vista;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author dam
 */
public class JPApp extends javax.swing.JPanel {

    BufferedImage bg = null;
    BufferedImage visionarios = null;
    BufferedImage nube1 = null;
    BufferedImage nube2 = null;
    BufferedImage nube3 = null;
    BufferedImage haloMountain = null;
    BufferedImage haloScenario = null;
    private float mousex;
    private float mousey;

    /**
     * Creates new form JPApp
     */
    public JPApp() {
        initComponents();

        try {
            bg = ImageIO.read(getClass().getResource("/recursos/bg.png"));
            nube1 = ImageIO.read(getClass().getResource("/recursos/nube1.png"));
            nube2 = ImageIO.read(getClass().getResource("/recursos/nube2.png"));
            nube3 = ImageIO.read(getClass().getResource("/recursos/nube3.png"));
            visionarios = ImageIO.read(getClass().getResource("/recursos/visionarios.png"));
            haloMountain = ImageIO.read(getClass().getResource("/recursos/haloMountain.png"));
            haloScenario = ImageIO.read(getClass().getResource("/recursos/haloScenario.png"));
        } catch (IOException ex) {
            Logger.getLogger(JPApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    double width = screenSize.getWidth();
    double height = screenSize.getHeight();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_formMouseMoved

    void animarEstrellas() {

    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.drawImage(bg, 0, 0, getBounds().width, getBounds().height, null);
        g2d.drawImage(nube1,(int)(mousex - (mousex  * 0.3)),(int)(mousey - (mousey  * 0.3)) , getBounds().width, getBounds().height, null);
        g2d.drawImage(nube2, 0, 0, getBounds().width, getBounds().height, null);
        g2d.drawImage(nube3, 0, 0, getBounds().width, getBounds().height, null);
        g2d.drawImage(haloScenario, 0, 0, getBounds().width, getBounds().height, null);
        g2d.drawImage(visionarios, 0, 0, getBounds().width, getBounds().height, null);
        g2d.drawImage(haloMountain, 0, 0, getBounds().width, getBounds().height, null);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
